
- name: Install common packages
  # become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - python3-pip
    update_cache: yes
    state: present

- name: Install pip dependencies
  # become: true
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3
    