- name: Install libs & packages
  hosts: app
  become: true
  roles:
    - role: common
      tags: ["install"]
    - role: geerlingguy.docker
      tags: ["install"]

- name: Deploy PHRH
  hosts: app
  become: true
  roles:
    - role: app
      tags: ["app"]
