- name: Create directory structure
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

# - name: Copy Server application
#   copy:
#     src: ../../../../server
#     dest: "{{ app_directory }}"

# - name: Copy Client Application
#   copy:
#     src: ../../../../client
#     dest: "{{ app_directory }}"

# - name: Login to Docker registry
#   docker_login:
#     username: "{{ docker_username }}"
#     password: "{{ docker_password }}"

# - name: Build and push docker image client
#   docker_image:
#     build:
#       path: /home/ubuntu/phrh/client
#     name: "{{ phrh_client_image }}"
#     tag: "{{ phrh_client_tag }}"
#     push: yes
#     source: build
#   notify: restart docker stack
#   tags: ["build", "redeploy"]

# - name: Build and push docker image server
#   docker_image:
#     build:
#       path: /home/ubuntu/phrh/server
#     name: "{{ phrh_server_image }}"
#     tag: "{{ phrh_server_tag }}"
#     push: yes
#     source: build
#   notify: restart docker stack
#   tags: ["build", "redeploy"]

- name: Copy docker-compose configuration file
  template:
    src: templates/docker-compose.yml
    dest: "{{ app_directory }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: restart docker stack
  tags: ["compose"]

- name: start docker stack
  docker_compose:
    project_src: "{{ app_directory }}"
