version: "3"
services:
  app:
    container_name: app
    image: blyndusk/ssdp-api:latest
    restart: always
    # build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"