version: "3"
services:
  phrh-db:
    container_name: phrh-db
    image: mongo
    volumes:
      - "{{ phrh_db_folder }}:/data/db"
    ports:
      - "{{ phrh_db_port }}:27017"
  phrh-server:
    container_name: phrh-server
    build: ./server/
    restart: always
    ports:
      - "{{ phrh_server_port }}:3001"
    depends_on:
      - phrh-db
  phrh-client:
    container_name: phrh-client
    build: ./client/
    restart: always
    ports: 
      - "{{ phrh_client_port }}:80"