version: "3"
services:
  phrh-db:
    container_name: phrh-db
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
  phrh-server:
    container_name: phrh-server
    image: blyndusk/phrh-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - phrh-db
  phrh-client:
    container_name: phrh-client
    image: blyndusk/phrh-client
    restart: always
    ports: 
      - 3000:80