version: "3"
services:
  phrh-db:
    container_name: phrh-db
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - database
  phrh-server:
    container_name: phrh-server
    build: ../server/
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - phrh-db
    networks:
      - database
  phrh-client:
    container_name: phrh-client
    build: ../client/
    restart: always
    ports: 
      - 3000:80 
    networks:
      - database

networks:
  database: