name: Client CI
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: install
      run: npm install
      working-directory: ./client
      env:
        CI: ""

    - name: lint
      run: npm run lint
      working-directory: ./client
      env:
        CI: ""

    - name: build
      run: npm run build
      working-directory: ./client
      env:
        CI: ""
