name: Main Workflow
on: 
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: install
      run: npm install
      working-directory: ./client

    - name: lint
      run: npm run lint
      working-directory: ./client

    - name: build
      run: npm run build
      working-directory: ./client

    - name: test
      run: npm run test
      working-directory: ./client